DOMAIN = "nice"

CONF_CONTROLLERS = "controllers"
CONF_COVERS = "covers"
CONF_IMAGE_AREA = "image_area"
CONF_CIW_MANAGERS = "ciw_managers"
CONF_PRESETS = "presets"

CONF_TITLE = "title"
CONF_SERIAL_PORT = "serial_port"
CONF_ADD_ANOTHER = "add_another"
CONF_CONTROLLER = "controller"
CONF_ADDRESS = "address"
CONF_NODE = "node"
CONF_DROP = "drop"
CONF_HAS_IMAGE_AREA = "has_image_area"
CONF_IMAGE_BORDER_BELOW = "image_border_below"
CONF_IMAGE_HEIGHT = "image_height"
CONF_IMAGE_ASPECT_RATIO_CHOICE = "image_aspect_ratio_choice"
CONF_IMAGE_ASPECT_RATIO_OTHER = "image_aspect_ratio_other"
CONF_SCREEN_COVER = "screen_cover"
CONF_SENSOR_PREFS = "sensor_prefs"
CONF_MASK_COVER = "mask_cover"
CONF_ASPECT_RATIO_MODE = "aspect_ratio_mode"
CONF_BASELINE_DROP = "baseline_drop"
CONF_ACTION = "action"
CONF_SELECT = "select"
CONF_COVER = "cover"
CONF_DROPS = "drops"
CONF_ASPECT_RATIO = "aspect_ratio"
CONF_FORCE_DIAGONAL_IMPERIAL = "force_diagonal_imperial"

CHOICE_ASPECT_RATIO_16_9 = "aspect_ratio_16_9"
CHOICE_ASPECT_RATIO_2_35_1 = "aspect_ratio_2_35_1"
CHOICE_ASPECT_RATIO_4_3 = "aspect_ratio_4_3"
CHOICE_ASPECT_RATIO_OTHER = "aspect_ratio_other"

SERVICE_APPLY_PRESET = "apply_preset"
SERVICE_SET_ASPECT_RATIO = "set_aspect_ratio"
SERVICE_SET_DROP_PERCENT = "set_drop_percent"

ACTION_ADD_CIW = "Add CIW Manager"
ACTION_DEL_CIW = "Delete CIW Manager(s)"
ACTION_ADD_PRESET = "Add Preset"
ACTION_DEL_PRESET = "Delete Preset(s)"
ACTION_SENSOR_PREFS = "Sensor Preferences"
