apply_preset:
  name: Apply Preset
  description: Move a set of covers to preset positions.
  fields:
    name:
      name: Name
      description: The name of the preset.
      required: true
      example: Preset 1
      selector:
        text:

set_aspect_ratio:
  name: Set Aspect Ratio
  description: Set the screen and mask to the specified aspect ratio.
  fields:
    name:
      name: Name
      description: The name of the CIW Manager.
      required: true
      example: CIW Manager 1
      selector:
        text:
    aspect_ratio:
      name: Aspect Ratio
      description: The target aspect ratio.
      required: true
      example: 1.7778
      selector:
        number:
          min: 0.4
          max: 3.5
          mode: box

set_drop_percent:
  name: Set Cover Drop Percent
  description: Set the Cover to the specified drop in percent
  target:
    entity:
      integration: nice
      domain: cover
  fields:
    drop_percent:
      name: Drop Percent
      description: The drop in percent (accuracy 0.1%)
      required: true
      example: 82.5
      selector:
        number:
          min: 0.0
          max: 100.0
          mode: box
