apply_preset:
  fields:
    name:
      required: true
      example: Preset 1
      selector:
        text:

reconnect:

set_drop_percent:
  target:
    entity:
      integration: nice
      domain: cover
  fields:
    drop_percent:
      required: true
      example: 82.5
      selector:
        number:
          min: 0.0
          max: 100.0
          mode: box

send_simple_command:
  target:
    entity:
      integration: nice
      domain: cover
  fields:
    command:
      required: true
      example: "move_up"
      selector:
        select:
          translation_key: "simple_command"
          options:
            - "stop"
            - "move_down"
            - "move_up"
            - "move_pos_1"
            - "move_pos_2"
            - "move_pos_3"
            - "move_pos_4"
            - "move_pos_5"
            - "move_pos_6"
            - "move_up_step"
            - "move_down_step"
            - "store_pos_1"
            - "store_pos_2"
            - "store_pos_3"
            - "store_pos_4"
            - "store_pos_5"
            - "store_pos_6"
            - "del_pos_1"
            - "del_pos_2"
            - "del_pos_3"
            - "del_pos_4"
            - "del_pos_5"
            - "del_pos_6"

refresh_position:
  target:
    entity:
      integration: nice
      domain: cover
